### ISSUE TITLE
PHP Fatal error when running postinstall

### ISSUE THREAD

**Issue by natea** [qpleple/wordpress-on-dotcloud#2]
I'm trying to deploy Wordpress to Dotcloud using your scripts, and see this error in the log:

```
18:59:19: [www.0] Running postinstall script...
18:59:21: [www.0] PHP Fatal error:  Call-time pass-by-reference has been removed in /home/dotcloud/rsync-1353715101184/dotcloud-scripts/feed-wp-config.php on line 86
```

Line 86 in feed-wp-config.php is:

```
$content = preg_replace('/(define\(\'' . $property . '\', \')(.*)(\'\);)/', '${1}' . $value . '${3}', $content, -1, &$count);
```

When I go to the Wordpress start page it says, "There doesn't seem to be a wp-config.php file. I need this before we can get started."

Any ideas?

**Comment by aitherios** [comment]
Just referencing the solution: http://stackoverflow.com/questions/13553698/call-time-pass-by-reference-has-been-removed

**Comment by qpleple** [comment]
Thanks guys!
